// frontend/lib/canon/spaces/_architect/.registrations/space_auth_registration.dart
//
// ─────────────────────────────────────────────────────────────────────────────
// AUTO-GENERATED STUB — safe to edit
// ─────────────────────────────────────────────────────────────────────────────
//   Generated by lib/core/sync (ArchitectRegistrationSyncJob) on 2026-05-06.
//   This file will NOT be overwritten on future sync runs.
//
// HOW TO ADD A SCREEN — two imports is always enough:
//
//   Import 1: the shell root of the screen
//     import '../../space_auth/{name}_views/shell_{name}_root.dart';
//
//   Import 2: any enums the shell constructor needs as arguments
//     import '../../space_auth/{name}_views/layout_{name}_config.dart';
//
//   Then add an ArchitectScreenEntry to the screens list:
//     ArchitectScreenEntry(
//       id:      'screen_space_auth_foo',
//       label:   'Foo',
//       description: 'What this screen does.',
//       builder: () => const ShellSpaceAuthRoot(mode: SpaceAuthMode.foo),
//     ),
//
// ─────────────────────────────────────────────────────────────────────────────

import 'package:flutter/material.dart';

import '../architect_model/architect_screen_registry.dart';

// Import 1: import '../../space_auth/{views_folder}/shell_{name}_root.dart';
// Import 2: import '../../space_auth/{views_folder}/layout_{name}_config.dart';

// ─────────────────────────────────────────────────────────────────────────────
// CONFIG
// ─────────────────────────────────────────────────────────────────────────────

const _kId     = 'space_auth';
const _kLabel  = 'space_auth';
const _kIcon   = Icons.lock_outline_rounded;
const _kAccent = Color(0xFF9933FF);

// ─────────────────────────────────────────────────────────────────────────────
// END CONFIG BLOCK
// ─────────────────────────────────────────────────────────────────────────────

final ArchitectSpace kRegisterSpaceAuth = ArchitectSpace(
  id:      _kId,
  label:   _kLabel,
  icon:    _kIcon,
  accent:  _kAccent,
  screens: const [],   // ← add ArchitectScreenEntry items here
);
