// frontend/lib/canon/spaces/_architect/architect_model/architect_auto_registry.dart
//
// ─────────────────────────────────────────────────────────────────────────────
// AUTO-GENERATED — do not edit by hand
// ─────────────────────────────────────────────────────────────────────────────
//   Regenerated by lib/core/sync (ArchitectRegistrationSyncJob) on 2026-05-04.
//   Run: cd frontend && dart run lib/core/sync/sync_runner.dart
//   Or start the watcher: dart run lib/core/sync/sync_watcher.dart
// ─────────────────────────────────────────────────────────────────────────────
//
// WHY THIS FILE PREVIOUSLY CONTAINED $imports AND $entries LITERALLY:
//   The sync ran while the .registrations/ folder was empty (the folder had
//   just been renamed from architect_registrations). The sync found no
//   registration files, so both variables evaluated to empty strings.
//   Dart string interpolation in the template produced blank lines, but the
//   file was valid Dart with nothing between the import and the list.
//   The version you saw with literal $imports/$entries was a stale copy that
//   had never been processed — it was the template string itself, not output.
//   Fix: run the sync once after the path update below lands in sync_config.dart.

import 'architect_screen_registry.dart';

import '../.registration/space_auth_registration.dart';
// import '../.registration/space_value_registration.dart';
import '../.registration/space_admin_registration.dart';
// import '../.registration/space_site_registration.dart';
import '../.registration/space_dev_registration.dart';

// ─────────────────────────────────────────────────────────────────────────────
// kArchitectSpaces — assembled from all registration files
// ─────────────────────────────────────────────────────────────────────────────

final List<ArchitectSpace> kArchitectSpaces = [
  kRegisterSpaceAuth,
  // kRegisterSpaceValue,
  kRegisterSpaceAdmin,
  // kRegisterSpaceSite,
  kRegisterSpaceDev,
];