// frontend/lib/canon/spaces/_architect/architect_model/architect_auto_registry.dart
//
// ─────────────────────────────────────────────────────────────────────────────
// AUTO-GENERATED — do not edit by hand
// ─────────────────────────────────────────────────────────────────────────────
//   Regenerated by lib/core/sync (ArchitectRegistrationSyncJob) on 2026-05-06.
// ─────────────────────────────────────────────────────────────────────────────

import 'architect_screen_registry.dart';

import '../.registrations/space_admin_registration.dart';
import '../.registrations/space_auth_registration.dart';
import '../.registrations/space_dev_registration.dart';
import '../.registrations/space_discovery_registration.dart';

// ─────────────────────────────────────────────────────────────────────────────
// kArchitectSpaces — assembled from all registration files
// ─────────────────────────────────────────────────────────────────────────────

final List<ArchitectSpace> kArchitectSpaces = [
  kRegisterSpaceAdmin,
  kRegisterSpaceAuth,
  kRegisterSpaceDev,
  kRegisterSpaceDiscovery,
];
