// frontend/lib/spaces/_architect/architect_registrations/space_admin_registration.dart
//
// ─────────────────────────────────────────────────────────────────────────────
// AUTO-GENERATED STUB — safe to edit
// ─────────────────────────────────────────────────────────────────────────────
//   Generated by lib/core/sync (ArchitectRegistrationSyncJob) on 2026-05-03.
//   This file will NOT be overwritten on future sync runs.
//   Add screen imports + ArchitectScreenEntry items to the screens list below.
// ─────────────────────────────────────────────────────────────────────────────
//
// HOW TO ADD A SCREEN:
//   1. Import the screen widget at the top of this file
//   2. Add an ArchitectScreenEntry to the screens list
//   3. Save — sync_watcher.dart updates architect_auto_registry.dart automatically

import 'package:flutter/material.dart';

import '../architect_model/architect_screen_registry.dart';

// ─────────────────────────────────────────────────────────────────────────────
// CONFIG — update icon + accent to match the space visual identity
// ─────────────────────────────────────────────────────────────────────────────

const _kId     = 'space_admin';
const _kLabel  = 'space_admin';
const _kIcon   = Icons.admin_panel_settings_outlined;
const _kAccent = Color(0xFFFAAF2E);

// ─────────────────────────────────────────────────────────────────────────────
// END CONFIG BLOCK
// ─────────────────────────────────────────────────────────────────────────────

final ArchitectSpace kRegisterSpaceAdmin = ArchitectSpace(
  id:      _kId,
  label:   _kLabel,
  icon:    _kIcon,
  accent:  _kAccent,
  screens: const [],   // ← import screen widgets above and add entries here
);
